### PR TITLE
Fix Status::vm* missing for kernel thread

### PR DESCRIPTION
**Pull request by dalance**
Kernel thread like `kthreadd`, `ksoftirqd`,,, don't have `Vm*` entries in `/proc/*/status`.
So all these entries changed to `Option` and added test for `kthreadd`.

### CODE REVIEW

**Comment by eminence** [comment]
Thanks!

**Comment by dalance** [comment]
Could you publish this version?

**Comment by eminence** [comment]
Done!

**Comment by dalance** [comment]
Thanks!

**Pull request merged**
