### PR TITLE
Add support for /proc/uptime

### PR DESCRIPTION
**Pull request by oblique**
Support for `/proc/uptime` was missing.

### CODE REVIEW

**Comment by oblique** [comment]
@eminence ping

**Comment by eminence** [comment]
Thanks for the ping (and thanks for the PR).  This looks good to me, except for the typo causing the build error

**Comment by oblique** [comment]
Oops! Fixed. I removed the `_secs` suffix. If you prefer it let me know and I will add it.

**Comment by oblique** [comment]
Fixed the test case issue for 1.34.0

**Review by eminence — APPROVED** [review]

**Comment by eminence** [comment]
We are green.  Thanks!

**Pull request merged**
