### PR TITLE
Dependency upgrades (rustix, criterion)

### PR DESCRIPTION
**Pull request by najaco**
Upgrades the following crates:
- `rustix`: 0.37.0 ➡️ 0.38.4
- `criterion`: 0.3 ➡️ 0.5

### CODE REVIEW

**Comment by najaco** [comment]
@eminence any thoughts?

**Comment by eminence** [comment]
LGTM, thanks

**Comment by najaco** [comment]
@eminence Thank you for taking a look. Any idea when we expect 0.16.0 to be released? Otherwise, is it possible that a patch version could be released with this upgrade?

**Comment by dingelish** [comment]
Friendly asking, any updates on the 0.16.0 release? Thanks!

**Comment by eminence** [comment]
0.16.0 is now released on crates.io

**Pull request merged**
