### PR TITLE
Add Android support

### PR DESCRIPTION
**Pull request by fabricedesre**
This adds support for android targets. Changes needed are:
- use the android specific version of the `MetadataExt` trait.
- use `libc::mode_t` instead of hardcoding the type for file modes (it's a u16 on 32bit Android targets).

### CODE REVIEW

**Comment by eminence** [comment]
LGTM, thanks!

I'm not an expert in android development, so a quick question for you:  do you have any recommendations on testing android in CI?   Is running `cargo check --target aarch64-linux-android` sufficient?  Or are there other targets that should be also checked?

**Comment by fabricedesre** [comment]
Yes, running `cargo check --target aarch64-linux-android` is a good way to verify the Rust parts, while not having to deal with the link phase which is more annoying because you need an android sysroot.

**Comment by eminence** [comment]
Ok great.  I'll add that later.  Thank you!

**Comment by eminence** [comment]
This has now been published on crates.io as `v0.9.0`.  Thank you!

**Pull request merged**
